# defining controllers to joints
left_wheel_front:
  type:
  joint: wheel_front_left_joint
  pid: {p:100, i:0.01, d:10}

right_wheel_front:
  type:
  joint: wheel_front_right_joint
  pid: {p:100, i:0.01, d:10}

left_wheel_rear:
  type:
  joint: wheel_rear_left_joint
  pid: {p:100, i:0.01, d:10}

right_wheel_rear:
  type:
  joint: wheel_rear_right_joint
  pid: {p:100, i:0.01, d:10}